### PR TITLE
Create sr-SR.i18n.js

### PR DESCRIPTION
**Pull request by novicaz**
Serbian latin translation
https://en.wikipedia.org/wiki/Gaj%27s_Latin_alphabet

### CODE REVIEW

**Comment by ianmartorell** [comment]
See #195

**Comment by novicaz** [comment]
Seen, but, there is no other way to make it work, if i use sr-Latn or similar i"m seeing this error

=> Errors prevented startup:                  
   
   While building the application:
   appname/i18n/sr-Latn.i18n.json: Can't recognise 'sr-Latn' as a language-tag:
   `appname/i18n/sr-Latn.i18n.json'
   
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.                    
=> Errors prevented startup:                  
   
   While building the application:
   appname/i18n/sr-Latin.i18n.json: Can't recognise 'sr-Latin' as a language-tag:
   `appname/i18n/sr-Latin.i18n.json'

**Comment by novicaz** [comment]
Just one question please, do i have to Delete branch now or not? I"m total git n00b:)

**Comment by ianmartorell** [comment]
Sorry, there was a syntax error, it should work now. I wasn't getting that error though, but an "unexpected token"...

**Pull request merged**
