### PR TITLE
Create sr.i18n.js

### PR DESCRIPTION
**Pull request by novicaz**
Serbian cyrilic translation
https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet

### CODE REVIEW

**Comment by ianmartorell** [comment]
Does Serbian Cyrillic also have a four letter name like sr-SR? I would like to follow the same convention already in place with [pt](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/i18n/pt.i18n.js) and [zh](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/master/i18n/zh.i18n.js), where the big objects are only defined in the four letter files.

**Comment by novicaz** [comment]
Hello, both serbian latin and serbian cyrilic use one, two and three bytes long characters. In devise i18n for rails and loomio.org we used sr and sr-RS(first is cyrilic and second one is latin variant of serbian). Please see https://github.com/novicaz/loomio/blob/master/config/locales/frontpage.sr-RS.yml  ... I tryed in first place to use sr-RS but that didn"t work for me, then i just used sr-SR... now in dropdown menu of the language selector i see just sr-SR instead of the name of the language.. Have to say that my level of knowledge about meteor is still not enough to make it right way... Please just set it as it is used in loomio repository, that is done by using standards as is shown on one article about ISO standards related to keyboard layouts on wikipedia.

**Comment by novicaz** [comment]
Serbian Cyrillic = sr
Serbian Latin = idk how it is solved in meteor ecosys so i just set it to sr-SR

**Comment by ianmartorell** [comment]
Okay, so I see the problem is that both scripts have the same language code because they're indeed the same language. So I think the best will be to distinguish them like this:

`sr-Cyrl`: Serbian, Cyrillic script
`sr-Latn`: Serbian, Latin script

I don't like using `sr-SR` because it doesn't clearly say what script it's using. `sr-SR` and `sr` are the same thinig. What do you think?

**Comment by ianmartorell** [comment]
I took the language codes from this site: http://symbolcodes.tlt.psu.edu/bylanguage/serbocroatian.html

**Comment by novicaz** [comment]
If that is compatible with tap:i18n-ui i"m happy, cheers, regards from Serbia

**Pull request merged**
