### PR TITLE
logoutCallback

### PR DESCRIPTION
**Pull request by comerc**
https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/43

### CODE REVIEW

**Comment by lionellei** [comment]
Hi, how do I provide my own Meteor.logout callback function? Thanks.

**Comment by comerc** [comment]
See code: https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/blob/2c3739d2d5aaccebf5a61ef094120af3d8badb4a/login_buttons.js#L17

**Comment by ianmartorell** [comment]
I've updated [the README](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3#add-logout-callback)

**Comment by lionellei** [comment]
Thank you :)

**Pull request merged**
