### PR TITLE
Radio elements as extra signup fields. 

### PR DESCRIPTION
**Pull request by shriharshmishra**
Hi, 

I have added code to allow radio elements as extra signup fields as well as the documentation. Please review. 

Thanks!

### CODE REVIEW

**Comment by ianmartorell** [comment]
Nice work!! But there seems to be a bug, the email field doesn't show up for some reason. Does this happen to you as well?

screen shot 2015-05-25 at 12 31 33

screen shot 2015-05-25 at 12 35 41

The same configuration with and without your patch makes the email field appear or disappear. Also, I don't know if it's a problem with this package or with the theme, but it doesn't work with fezvrasta's [bootstrap material design](https://github.com/FezVrasta/bootstrap-material-design):

screen shot 2015-05-25 at 12 32 23

**Comment by shriharshmishra** [comment]
I guess I know the problem. I will fix and revert. Thanks!

**Comment by shriharshmishra** [comment]
I have fixed the missing email issue.  Please check. 

I tried making this work with bootstrap material design but theirs seems to be some CSS or JS issue.

**Comment by ianmartorell** [comment]
Thanks, I did some minor changes too, so the inputs are in the same div and the spacing doesn't look weird.

**Comment by shriharshmishra** [comment]
Great! Thanks!

**Pull request merged**
